### ISSUE TITLE
🐛 [BUG REPORT]: Agent Infinite Loop on Non-Transient Errors

### ISSUE THREAD

**Issue by AbuYusof** [zaxbysauce/opencode-swarm#1875]
# 🐛 BUG REPORT: Agent Infinite Loop on Non-Transient Errors

**Filed by:** NORM Decision OS team  
**Date:** 2026-07-17  
**Affects:** Windows agents (all roles)  
**Priority:** HIGH (wasted tokens, time, work stoppage)  
**Filed against:** opencode-swarm (plugin guardrails)

---

## Summary

Agents enter **infinite retry loops** when hitting non-transient errors. They retry the same or similar command indefinitely, consuming 5000–15000 tokens per attempt, because:

1. **No error classification** — agents cannot distinguish transient errors from permanent blocks
2. **No `ParseError` coverage** — the STOP protocol covers L0–L5 errors but not command-generation failures  
3. **Sanitizer wrapper is brittle** — `#` comments + PowerShell `-Command` parameter = silent corruption  
4. **PATH restriction is over-aggressive** — `$env:PATH = 'C:\WINDOWS\System32;C:\WINDOWS'` removes `python`, `node`, `git`

---

### Evidence  

Every bash command on Windows is wrapped in this sanitizer script:  

```powershell
powershell -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -Command "
$ErrorActionPreference = 'Stop'; try {
   # Set scoped temp directory            ← END-OF-LINE COMMENT
   $env:TEMP = '...';
   # Note: LD_PRELOAD...                  ← ANOTHER COMMENT
   $dangerousVars = @('LD_PRELOAD', ...);
   ...
   cmd /c \"python script.py\";
} catch { ... }"
```

**Result:**  

```
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError
    + FullyQualifiedErrorId : MissingEndCurlyBrace
```

### Root Cause  

`#` in PowerShell is an **end-of-line comment**. When `-Command` normalizes line breaks, `#` comments **swallow everything after them** — including the closing `}` and `catch` block.  

### Impact  

- Agent receives `ParseError` — not a guardrail block, not a transient failure  
- Agent does **not** recognize `MissingEndCurlyBrace` as a STOP signal  
- Agent retries → same error → **loop forever**  
- Typical cost: **8000–15000+ tokens** per loop cycle  

### Suggested Fix (Sanitizer)  

**Option A — Remove `#` comments:**  
```diff
- # Set scoped temp directory
+ <# Set scoped temp directory #>
```

**Option B — Use temp `.ps1` file (reliable):**  
```powershell
$tmp = "$env:TEMP\_ns_$(Get-Random).ps1"
@"
$ErrorActionPreference = 'Stop'
`$env:TEMP = '...'
python script.py
"@ | Out-File -FilePath $tmp -Encoding UTF8
powershell -ExecutionPolicy Bypass -File $tmp
Remove-Item $tmp -Force
```

**Option C — Use PowerShell here-string with pipe (proven workaround):**  
```powershell
$ @"
python code
"@ | python
```

---

### Evidence  

```powershell
$env:PATH = 'C:\WINDOWS\System32;C:\WINDOWS';
```

On Windows, `python.exe`, `node.exe`, `git.exe`, `npm.cmd` are in:  
- `C:\Users\<user>\AppData\Local\Programs\Python\Python312\`  
- `C:\Users\<user>\AppData\Local\Microsoft\WindowsApps\`  
- `C:\Program Files\Git\cmd\`  

**None of these are in the sanitized PATH.**  

### Result  

```
The term 'python' is not recognized as a name of a cmdlet...
```

### Impact  

- **Every legitimate bash command fails** on Windows unless the sandbox resolves full paths  
- Agent sees execution error, tries alternatives → waste loop  
- Tools that depend on `python`, `node`, `git`, `npm`, `pip` all break  

### Suggested Fix (Sanitizer)  

```diff
- $env:PATH = 'C:\WINDOWS\System32;C:\WINDOWS';
+ $env:PATH = 'C:\WINDOWS\System32;C:\WINDOWS;C:\Program Files\Git\cmd\;' +
+   [System.Environment]::GetEnvironmentVariable('PATH','User') + ';' +
+   [System.Environment]::GetEnvironmentVariable('PATH','Machine');
```

Or: **do not overwrite PATH at all** — restrict via `working_directory` and file-authority rules instead.  

---

### Evidence  

| Error | Layer | Agent Action |
|-------|-------|-------------|
| `WRITE_BLOCKED` | L4 | ✅ STOP |
| `BASH_WRITE_DETECTED` | L3 | ✅ STOP |
| `SCOPE_VIOLATION` | L5 | ✅ STOP |
| `Missing closing '}'` | None | ❌ **LOOP** |
| `ParserError` | None | ❌ **LOOP** |
| `'python' is not recognized` | None | ❌ **LOOP** |

The STOP protocol covers only known error patterns from L0–L5. Errors **outside** the 6-layer guardrails are invisible.  

### Suggested Fix  

**A. Add missing errors to STOP protocol:**  
```markdown
| `Missing closing '}'`, `MissingEndCurlyBrace`, `ParserError` | **L3.5** | Command-generation failure. STOP. |
| `not recognized`, `cmdlet not recognized` | **L3.5** | Command not in PATH. STOP. |
| `[sandbox] BLOCKED: Failed to wrap command` | **L0.5** | Sandbox wrapper failure. STOP. |
```

**B. General-purpose circuit breaker:** 3rd same-category error → STOP.  

**C. `tool-after.ts` hook** to detect `ParseError`/`MissingEndCurlyBrace` and inject STOP directive.  

---

## 🟩 Issue #4: `declare_scope` Gaps Cause SCOPE_VIOLATION Loops

The coder process starts with **empty scope**. Without `declare_scope`, every write hits `SCOPE_VIOLATION`. Coder tries alternatives (write → bash → python -c) — each blocked by a different layer.  

**Impact:** 3–7 wasted attempts per file = **15000–35000 tokens** per write.  

**Fix:** Default scope fallback (`src/**`) or block delegation with `"SCOPE_NOT_DECLARED"`.  

---

## 🟪 Issue #5: `#` Comment Hazard on All Shell Wrappers  

Same bug exists in `bash -c` inline scripts — only `#` comments are dangerous in all inline `-c` patterns.  

**Fix:** Never use `#` comments in inline `-c` scripts. Use temp files instead.  

---

## 📊 Token Waste Calculation  

| Scenario | Attempts | Tokens/Attempt | Total Waste |
|----------|----------|---------------|-------------|
| PowerShell ParseError loop | 5–15 | 8000–15000 | **40K–225K** |
| PATH 'not recognized' loop | 3–8 | 5000–8000 | **15K–64K** |
| SCOPE_VIOLATION multi-tool | 3–7 | 2000–5000 | **6K–35K** |

**Per-session impact: 60K–324K wasted tokens.**  

---

## 🏗 Proposed Architecture: Layer 3.5  

```
L0 — Spec Drift Gate
L1 — Interpreter Gating
L2 — Destructive Command Protection
L3 — Shell Write Detection
L3.5 — Command Generation Error Classification (NEW)
    ├─ ParseError → STOP
    ├─ CommandNotFound (not recognized) → STOP
    ├─ SandboxWrapperFail → STOP
    └─ CircuitBreaker (3rd failure) → STOP
L4 — File Authority
L5 — Scope Guard
```

### Implementation  

- `tool-after.ts` hook detects `ParseError`/`MissingEndCurlyBrace`/`not recognized` → injects STOP
- Circuit breaker: 3rd same-category error → hard STOP
- Agent training: update STOP protocol with new error categories  

---

## ✅ Acceptance Criteria  

1. [ ] PowerShell `-Command` with inline scripts parses correctly on Windows  
2. [ ] `python`, `node`, `git` available in sanitized bash commands  
3. [ ] Agents STOP immediately on `ParseError` / `MissingEndCurlyBrace`  
4. [ ] Agents STOP immediately on `not recognized` / `not found`  
5. [ ] Circuit breaker trips at 3rd same-category failure  
6. [ ] `declare_scope` default fallback prevents SCOPE_VIOLATION loops  
7. [ ] STOP protocol updated with all known error patterns  

---

## 📁 Files Referenced  

| File | Role |
|------|------|
| `src/hooks/guardrails/tool-before.ts` | 6-layer pipeline builder |
| `src/hooks/guardrails/shell-write-detect.ts` | L3 stop patterns |
| `src/hooks/guardrails/destructive-command.ts` | L2 |
| `src/hooks/guardrails/file-authority.ts` | L4 |
| `src/hooks/scope-guard.ts` | L5 |
| `src/agents/index.ts` | Agent factory |

---

## 🧪 Reproduction  

1. On Windows, ask **any agent** to run: `python -c "print('hello')"`  
2. Sanitizer wraps in PowerShell with `#` comments  
3. Returns `Missing closing '}'` parse error  
4. Agent retries → loop  

**Direct:**  
```powershell
powershell -Command "try { # comment } catch { }"
# → Missing closing '}'
```

---

**Comment by zaxbysauce** [comment]
@AbuYusof thanks again for the detailed bug report. We always prioritize user issues over roadmap items so this is going in now. Your previous issue should be resolved in PR 1876 which will merge shortly once all checks are run.

**Comment by zaxbysauce** [comment]
Implemented in draft PR #1878: https://github.com/ZaxbyHub/opencode-swarm/pull/1878

The fix closes the recurrence paths together: the Windows sandbox wrapper now uses encoded PowerShell with a safe inherited tool PATH and exact exit propagation; parser/command-not-found/wrapper failures stop immediately; repeated permanent failures trip a bounded third-occurrence circuit; and Task scope is identity-bound and enforced for direct and shell writes across every delegation path.

Regression coverage includes real Windows wrapper execution, parser and command availability checks, invocation reset semantics, Task `callID` correlation, scope lifecycle cleanup/containment, shell/direct alternate-tool enforcement, and transactional multi-target extraction. No migration is required.

The branch has passed the local CI-equivalent unit run, focused sandbox/security/smoke suites, typecheck, lint, build, Node ESM import, repro-704 startup deadline, drift/tool-registration checks, and packed-artifact smoke. Remote PR checks are being monitored before the PR is marked ready.

**Comment by zaxbysauce** [comment]
Confirmed all three core issues in the bug report:

**Issue #1 (PowerShell `#` comment → ParseError):** Verified in `src/sandbox/win32/restricted-environment-executor.ts:378-413`. The `psScript` template literal contains `#`-prefixed comments on lines 381, 385, 388-389, and 405. When this is passed via `-Command "${psScript}"` at line 413, PowerShell's end-of-line `#` comment semantics cause the closing `}` and `catch` block to be swallowed, producing `MissingEndCurlyBrase`.

**Issue #2 (PATH restriction):** Verified at line 148 — `getSafeWindowsPath()` returns only `${sysRoot}\System32;${sysRoot}`, excluding all user-installed tool paths (python, node, git, npm). Assigned at line 386.

**Issue #3 (No shell-level circuit breaker):** The existing circuit breaker (`src/background/circuit-breaker.ts`) is scoped to PR monitoring. The `architect_loop_detected` / `coder_retry_circuit_breaker` events exist for agent delegation but not for repeated shell execution failures (ParseError, command-not-found).

Fix has already been implemented in PR #1878 per the maintainer's comments. Closing as addressed.

**Comment by AbuYusof** [comment]
# Reply to Issue #1875 — Retry Loop Evidence for Issue #3

**Re: "Needs more info" — Infinite retry loop with MissingEndCurlyBrace**

Here are concrete logs from a real Windows session where an agent was stuck in an unbounded retry loop. This confirms the error classification gap (Issue #3 in the bug report) and the `#` comment parser crash (Issue #1).

---

## Session: `ses_09449878effeaSJmtoOip9H8Q5`
**Date:** 2026-07-16  
**Duration:** 20:14 – 20:46 UTC (32 minutes)  
**Source:** `shell-audit.jsonl` + `events.jsonl` + `telemetry.jsonl`

---

## 1. The Failing Command (retried identically x2)

The following PowerShell command was attempted **identically at least twice** (lines 210 and 222 in shell-audit.jsonl):

```powershell
powershell -ExecutionPolicy Bypass -NoProfile -WindowStyle Hidden -Command "
$ErrorActionPreference = 'Stop'; try {
  # Set scoped temp directory                                 ← comment inside -Command
  $env:TEMP = '~\AppData\Local\Temp';
  # Restrict PATH to safe system paths                        ← comment inside -Command
  $env:PATH = 'C:\WINDOWS\System32;C:\WINDOWS';
  # Note: LD_PRELOAD...                                       ← comment inside -Command
  ...
  # Execute the command...                                    ← comment inside -Command
  cmd /c \"cmd /c python ...\";
} catch {
  Write-Error $_.Exception.Message;
  exit 1;
}"
```

**Note:** This is the sandbox wrapper's own template — the `#` comments are part of `restricted-environment-executor.ts`, not user code.

---

## 2. The Error

```
Missing closing '}' in statement block or type definition.
ParserError: MissingEndCurlyBrace
```

**Root cause:** When `cmd.exe` normalizes the `-Command` string, it strips or normalizes inline `#` comments. The `}` character that immediately follows the `# Execute the command...` comment is lost, producing an unbalanced PowerShell script. The braces no longer match.

---

## 3. The Full Retry Sequence (25+ attempts, 32 minutes)

| # | Time | Form | Result |
|---|------|------|--------|
| 1 | 20:14:40 | `cd ... && python scripts/generate_evidence_index.py` | `sandbox_wrap` |
| 2 | 20:14:45 | Same command | `sandbox_wrap` |
| 3 | 20:14:50 | `python C:\...\generate_evidence_index.py` | `sandbox_wrap` |
| 4 | 20:14:55 | Same command | `sandbox_wrap` |
| 5 | 20:15:00 | `cmd /c "cd /d ..."` | `sandbox_wrap` |
| 6 | 20:15:06 | `python C:\...` | `sandbox_wrap` |
| 7 | 20:15:11 | `powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "..."` | `sandbox_wrap` |
| 8 | 20:15:15 | `cmd /c "cd /d ..."` | `sandbox_wrap` |
| 9 | 20:15:21 | Same command | `sandbox_wrap` |
| 10 | 20:15:26 | `python C:\...` | `sandbox_wrap` |
| 11 | 20:15:34 | `powershell -NoProfile -WindowStyle Hidden -Command "$TEMP=..."` | ✅ Simple |
| 12 | 20:15:38 | `python C:\...` | `sandbox_wrap` |
| 13-16 | 20:42-43 | Various `python`, `cmd /c`, `powershell -File` attempts | Mixed |
| **17** | **20:45:11** | **⚠️ PowerShell with # comments → MissingEndCurlyBrace** | **FAIL** |
| 18 | 20:45:16 | `cmd /c python` | `sandbox_wrap` |
| 19 | 20:45:32 | `python scripts/...` | `sandbox_wrap` |
| 20 | 20:45:40 | `powershell ... $env:PATH=...` | ✅ Simple |
| 21 | 20:45:44 | `powershell ... python ...` | ✅ Simple |
| 22 | 20:45:48 | `cmd /c python` | `scope_violation` |
| 23 | 20:45:51 | `cmd /c python scripts` | `sandbox_wrap` |
| 24 | 20:46:02 | `powershell -NoProfile -Command "python..."` | ✅ Simple |
| **25** | **20:46:09** | **⚠️ Same PowerShell with # comments → MissingEndCurlyBrace** | **FAIL** |

---

## 4. Circuit Breaker Analysis: NOT FIRING

| What was expected (FR-024/SC-023) | What actually happened |
|-----------------------------------|----------------------|
| Halt after 3 consecutive failures | **25+ attempts, 32 minutes of looping** |
| `circuit_breaker` event recorded | **Zero events** in `events.jsonl` or `telemetry.jsonl` |
| `loop_detected` event recorded | **Zero events** across all session files |
| `Coder attempt N/3` message | **Not present anywhere** in the session logs |

**The circuit breaker is not triggering because `MissingEndCurlyBrace` is never classified as a permanent failure.** It appears to be treated as a transient error (or falls through an unhandled error category), so the retry budget never depletes.

---

## 5. Key Takeaways

1. **`#` comment in `-Command` is a genuine PowerShell parser trap** — `cmd.exe` line normalization drops the `#`-prefixed lines, breaking brace matching. This is confirmed in `restricted-environment-executor.ts` line 389.

2. **The `sandbox_wrap` interceptor amplifies the problem** — every Python / `cmd` command gets wrapped in a PowerShell template that contains `#` comments. Even if the original command is valid, the wrapper template itself can break.

3. **Error classification gap is real** — `MissingEndCurlyBrace` is a permanent parse error, not a transient network blip. The system fails to recognize it as a non-transient failure and the circuit breaker never fires.

4. **PR #1878 addresses all three root causes** — the encoded PowerShell, safe inherited PATH, `#`→`<# #>` comment fix, and bounded third-occurrence circuit breaker should resolve this class of loops entirely.

---

*Logs extracted from shell-audit.jsonl, events.jsonl, and telemetry.jsonl — available on request if raw files are needed.*

**Comment by AbuYusof** [comment]
*Subject:* Re: [ZaxbyHub/opencode-swarm] 🐛 [BUG REPORT]: Agent Infinite
Loop on Non-Transient Errors (Issue #1875
<https://github.com/ZaxbyHub/opencode-swarm/issues/1875>) — Additional
Evidence for Issues #3 <https://github.com/ZaxbyHub/opencode-swarm/issues/3>
 & #4 <https://github.com/ZaxbyHub/opencode-swarm/pull/4>

*To:* zaxbysauce / ZaxbyHub/opencode-swarm
------------------------------

***@***.**** <https://github.com/zaxbysauce> thanks for the incredibly
fast turnaround on PR #1878
<https://github.com/ZaxbyHub/opencode-swarm/pull/1878> — great to see this
prioritized.

I've prepared the evidence you requested for Issue #3
<https://github.com/ZaxbyHub/opencode-swarm/issues/3> and Issue #4
<https://github.com/ZaxbyHub/opencode-swarm/pull/4>. It's attached as a zip
archive (powershell-loop-evidence.zip). Here's the breakdown:
------------------------------

*Issue #3 <https://github.com/ZaxbyHub/opencode-swarm/issues/3> — Infinite
Retry on MissingEndCurlyBrace (EVIDENCE ATTACHED)*

The attached folder contains concrete logs showing an agent looping on this
exact error:

*Session ID:* ses_09449878effeaSJmtoOip9H8Q5
*Duration:* 32 minutes (20:14 → 20:46 UTC, July 16)
*Total attempts:* 25 — *all failed*
*Circuit breaker events:* *ZERO*

*Key files in the archive:*

   - shell-audit-filtered.md — Filtered entries
   from .swarm/session/shell-audit.jsonl showing lines 210 and 222: two
   identical powershell -Command invocations with inline # comments that both
   produced MissingEndCurlyBrace. The timeline shows the full 25-attempt
   sequence.
   - failing-commands.md — The two failing commands with context.
   - retry-loop-timeline.md — Timeline showing all command variations
   attempted.
   - circuit-breaker-absent.md — *The critical finding*: I searched
   both .swarm/events.jsonl and .swarm/telemetry.jsonl for
   any circuit_breaker event — *zero records found*. The circuit breaker
   did not recognize MissingEndCurlyBrace as a permanent (non-transient) parse
   error, so the agent wasted all 25 retries.
   - live-demo-fail.md — While preparing this evidence, the *exact same
   error reproduced live* — even a simple mkdir command failed through the
   sandbox wrapper. I couldn't create the evidence folder via bash at all; I
   had to use direct file write tools instead.
   - raw-missing-end-curly-brace.md — The full log of 5 live reproduction
   attempts.

*The pattern is clear:* Commands without # comments
(simple Get-ChildItem, cmd /c python) succeed. Commands that go through the
sandbox wrapper with the # comment template consistently
produce MissingEndCurlyBrace. The error is deterministic — a parse error —
not a transient failure. The circuit breaker should classify it as
permanent on the second identical occurrence.
------------------------------

*Issue #4 <https://github.com/ZaxbyHub/opencode-swarm/pull/4> —
declare_scope Gaps*

The empty scope scenario I observed happened specifically during *Phase 1
pre-planning* (the initial Board Baseline phase). At that point,
no declare_scope had been called yet because the plan was still being
created/negotiated. The agent configuration was the default mega-swarm
configuration — I hadn't modified any agent permission profiles.

The scope_violation events in shell-audit.jsonl (lines 2, 13, 25, 204, 218)
all show "declaredScope": "" — an empty string — which triggers a scope
violation on any bash command that touches a path outside the working
directory. This suggests the scope guard defaults to empty when no explicit
scope has been declared, which may be too restrictive for initial discovery
tasks.
------------------------------

Thanks again for the quick action on this. Happy to provide any additional
logs or walk through a live repro session if helpful.

**Comment by AbuYusof** [comment]
[image: Screenshot 2026-07-17 150957.png][image: Screenshot 2026-07-17
150852.png]

**Comment by zaxbysauce** [comment]
Implemented end to end in #1878 and verified against the later reporter comments, including the 32-minute / 25-attempt session, the PowerShell `MissingEndCurlyBrace` parser failure, the absence of `circuit_breaker` / `loop_detected`, and the Phase-1 empty-scope report.

Permanent recurrence guards now cover the full failure chain:

- Windows PowerShell commands use encoded transport, inherit the tool PATH safely, and preserve the exact child exit code.
- The unsupported Bash `args.env` mutation was removed; the wrapper-owned environment is the single wired path.
- Parser failures, command-not-found failures, and wrapper failures stop immediately instead of consuming the general retry budget.
- Other permanent failures hard-stop at 3/3; STOP advice and `loop_detected` emit exactly once on the false-to-true hard-stop transition.
- Pending shell outcomes are bound to the owning agent and invocation. Late results after reset, same-agent reinvocation, or cross-agent handoff are ignored even when tool call IDs collide.
- Phase-1 dispatch to the canonical `coder` role before an approved plan fails closed with `SCOPE_NOT_DECLARED` under any user-defined swarm ID; no empty scope or child state is published. Swarm IDs such as `mega`, `id`, `lowtier`, `modelrelay`, and unseen custom names receive identical role-based behavior.
- Scope state is identity-bound and lifecycle-safe, and multi-target write extraction is transactional.
- Native `apply_patch` framing and traversal validation are centralized and regression-covered, including every authority fixture that exposed the final CI failure.

The detailed swarm-review findings and the subsequent CI failures are also closed on final head `049c629b96f6b70e0d89aff6de16232475a22a66`:

- The Windows `%VAR%` temp-path injection found during review is fixed by keeping the absolute batch path inside PowerShell and exposing only a generated basename to `cmd.exe`, with delayed expansion disabled.
- Hard-stop immutability, category alternation, direct classifier behavior, bounded FIFO replacement, 1,000-character signal truncation, and remember/mark/forget lifecycle now have explicit regression coverage.
- Arbitrary non-empty swarm IDs and supported separators remain role-based; no configured swarm name is privileged.
- 18/18 unit shards passed: macOS 6/6, Ubuntu 6/6, Windows 6/6. The previously failing shard 3 passed on all three operating systems.
- Coverage, integration, smoke on macOS/Ubuntu/Windows, quality, security, package-check, drift, title, and PR standards all passed in exact-head run `29598639732`.
- Local final repair validation passed 119 focused Windows tests, typecheck, lint over 2,580 files, and diff hygiene.
- Sequential independent reviewer, test-engineer, closeout-reviewer, adversarial-critic, and post-CI assertion-review gates all approved the completed change.

PR #1878 is out of draft and ready for maintainer review: https://github.com/ZaxbyHub/opencode-swarm/pull/1878

**Comment by AbuYusof** [comment]
# Thank You — v7.122.1 Confirmation

**To the opencode-swarm team,**

Thank you for the rapid turnaround on v7.122.1. We have verified the release against our environment (Windows 11, PowerShell 7.6.2, Node.js 22.22.3) and can confirm that all reported issues from [#1875](https://github.com/ZaxbyHub/opencode-swarm/issues/1875) are resolved:

## Verified Fixes

| Issue | Symptom | Status in v7.122.1 |
|-------|---------|--------------------|
| **Non-transient retry loops** | Agent retried `MissingEndCurlyBrace` and `is not recognized` errors 25+ times across 32 minutes without a circuit breaker | ✅ `guardrails: stop non-transient command loops` — verified: `MissingEndCurlyBrace` now stops immediately |
| **Inline `#` comments breaking PowerShell `-Command`** | Sandbox wrapper template contained `#` comments that `cmd.exe` line-normalization stripped, breaking brace matching | ✅ `close issue 1875 review gaps` — comments migrated to `<# #>` blocks |
| **Restrictive PATH** | `getSafeWindowsPath()` limited PATH to `%SystemRoot%\System32;%SystemRoot%`, preventing `python`/`node`/`git` resolution | ✅ Safe inherited PATH in encoded PowerShell transport |
| **Circuit breaker absent** | No `circuit_breaker` or `loop_detected` events in telemetry despite 25+ consecutive failures | ✅ Third same-category failure now hard-stops with one-time `STOP` advisory and telemetry event |
| **Empty declare_scope** | Task delegation with no declared scope published empty scope state | ✅ `SCOPE_NOT_DECLARED` fail-closed before delegation |
| **bun:sqlite on Node.js** | Plugin crashed under Electron sidecar with `Cannot find module 'bun:sqlite'` | ✅ `node:sqlite` fallback (v7.121.4) — confirmed working in v7.122.0+ |

## Test Results

All local verification passes cleanly:
- ✅ `swarm_memory_recall` — No more `bun:sqlite` crash
- ✅ `get_qa_gate_profile` — Works correctly
- ✅ `test_council_rename_verify.py` — 22/22 PASS
- ✅ `smoke_verify.py` — 20/22 PASS (2 pre-existing Saudi compliance failures, unrelated)

## Evidence Logs Provided During Triage

The 25-attempt, 32-minute retry loop session (`ses_09449878effeaSJmtoOip9H8Q5`, 2026-07-16) with full `shell-audit.jsonl` excerpts was shared during triage and confirmed in the fix.

---

Once again, thank you for the professional and thorough work — from the initial triage acknowledgment within an hour, through the detailed PR with 34/34 CI checks passing across all three platforms, to the clean release. The `docs/releases/pending/1875-nontransient-error-loop.md` document will be a valuable reference for anyone debugging Windows sandbox issues going forward.

Best regards,  
AbuYusof
